language: java
install: mvn install

sudo: false

jdk:
  openjdk14

after_success:
  bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      g1377@protonmail.com
    on_success: never
    on_failure: always

